# Generated by Django 4.2.5 on 2023-09-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
