# Generated by Django 4.2.5 on 2023-09-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0002_rename_quntity_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_field', models.CharField(max_length=255)),
            ],
        ),
    ]
