# Generated by Django 4.2.5 on 2023-09-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0003_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
